name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.9

      - name: Install uv
        run: |
          curl -Ls https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          uv pip install -r requirements.txt
          # Or: uv pip install .[dev]  # if using a pyproject.toml with extras

      - name: Run pre-commit checks
        run: |
          uv pip install pre-commit
          pre-commit run --all-files

      - name: Run tests
        run: |
          uv pip install pytest  # If not already in requirements
          pytest tests
